module.exports = {
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      screens: {
        sm: "576px",
        md: "768px",
        lg: "1024px",
        xl: "1280px",
        "2xl": "1300px",
      },
      colors: {
        main_bg_color_light: "#010409",
        second_bg_color_light: "#0D1117",
        third_bg_color_dark: "#161B22",
        main_border_color_light: "#21262D",
        main_font_color_light: "#FFFFFF",
        second_font_color_light: "#9090A3",
        third_font_color_light: "#424356",
        fourth_font_color_light: "#BCBCCD",
        fifth_font_color_light: "#808193",
        blue_font_color: "#3161F1",
        yellow_font_color: "#FFB700",
        main_heighlight_color_light: "#723FC8",
        second_heighlight_color_light: "#343548",
        main_link_color_light: "#3692F0",
        rating_newbie: "#CCCCCC",
        rating_pupil: "#77FF77",
        rating_specialist: "#77DDBB",
        rating_expert: "#AAAAFF",
        rating_candidate_master: "#FF88FF",
        rating_master: "#FFCC88",
        rating_international_master: "#FFBB55",
        rating_grandmaster: "#FF7777",
        rating_international_grandmaster: "#FF3333",
        rating_legendary_grandmaster: "#AA0000",
        // dark mode colors
        main_bg_color_dark: "#FFFFFF",
        second_bg_color_dark: "#F7F7F7",
        third_bg_color_dark: "#E9ECEF",
        main_border_color_dark: "#DEE2E6",
        main_font_color_dark: "#212529",
        second_font_color_dark: "#495057",
        third_font_color_dark: "#6C757D",
        fourth_font_color_dark: "#ADB5BD",
        fifth_font_color_dark: "#CED4DA",
        main_heighlight_color_dark: "#007AFF",
        second_heighdark_color_dark: "#343548",
        main_link_color_dark: "#3692F0",
      },
      boxShadow: {
        custom: '0 4px 6px rgba(0, 0, 0, 0.1)',
      },
    },
  },
  plugins: [require("flowbite/plugin")],
};
